// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// engine_core //
// ----------- //

#define engine_core_wrap_target 8
#define engine_core_wrap 12
#define engine_core_pio_version 0

#define engine_core_offset_entry_crank 0u
#define engine_core_offset_entry_output 8u

static const uint16_t engine_core_program_instructions[] = {
    0xa02b, //  0: mov    x, ~null
    0x00c4, //  1: jmp    pin, 4
    0x0041, //  2: jmp    x--, 1
    0x0001, //  3: jmp    1
    0x4020, //  4: in     x, 32
    0x8000, //  5: push   noblock
    0x2020, //  6: wait   0 pin, 0
    0x0000, //  7: jmp    0
            //     .wrap_target
    0x80a0, //  8: pull   block
    0x6004, //  9: out    pins, 4
    0x603c, // 10: out    x, 28
    0x004b, // 11: jmp    x--, 11
    0xa003, // 12: mov    pins, null
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program engine_core_program = {
    .instructions = engine_core_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = engine_core_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config engine_core_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + engine_core_wrap_target, offset + engine_core_wrap);
    return c;
}
#endif

