// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------- //
// picospeed_decoder //
// ----------------- //

#define picospeed_decoder_wrap_target 1
#define picospeed_decoder_wrap 19
#define picospeed_decoder_pio_version 0

static const uint16_t picospeed_decoder_program_instructions[] = {
    0xa02b, //  0: mov    x, ~null
            //     .wrap_target
    0x01c3, //  1: jmp    pin, 3                 [1]
    0x0005, //  2: jmp    5
    0x0041, //  3: jmp    x--, 1
    0x0001, //  4: jmp    1
    0xa0c3, //  5: mov    isr, null
    0xe041, //  6: set    y, 1
    0x4041, //  7: in     y, 1
    0x403f, //  8: in     x, 31
    0x8000, //  9: push   noblock
    0xa02b, // 10: mov    x, ~null
    0x00ce, // 11: jmp    pin, 14
    0x004b, // 12: jmp    x--, 11
    0x000b, // 13: jmp    11
    0xa0c3, // 14: mov    isr, null
    0xe040, // 15: set    y, 0
    0x4041, // 16: in     y, 1
    0x403f, // 17: in     x, 31
    0x8000, // 18: push   noblock
    0xa02b, // 19: mov    x, ~null
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program picospeed_decoder_program = {
    .instructions = picospeed_decoder_program_instructions,
    .length = 20,
    .origin = -1,
    .pio_version = picospeed_decoder_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config picospeed_decoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + picospeed_decoder_wrap_target, offset + picospeed_decoder_wrap);
    return c;
}
#endif

// ---------- //
// inj_output //
// ---------- //

#define inj_output_wrap_target 0
#define inj_output_wrap 14
#define inj_output_pio_version 0

static const uint16_t inj_output_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0x002d, //  2: jmp    !x, 13
    0x80a0, //  3: pull   block
    0xa047, //  4: mov    y, osr
    0x0067, //  5: jmp    !y, 7
    0x0086, //  6: jmp    y--, 6
    0x80a0, //  7: pull   block
    0xa047, //  8: mov    y, osr
    0x006d, //  9: jmp    !y, 13
    0xa0e1, // 10: mov    osr, x
    0x6000, // 11: out    pins, 32
    0x008c, // 12: jmp    y--, 12
    0xa0e3, // 13: mov    osr, null
    0x6000, // 14: out    pins, 32
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program inj_output_program = {
    .instructions = inj_output_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = inj_output_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config inj_output_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + inj_output_wrap_target, offset + inj_output_wrap);
    return c;
}
#endif

// ---------- //
// ign_output //
// ---------- //

#define ign_output_wrap_target 0
#define ign_output_wrap 14
#define ign_output_pio_version 0

static const uint16_t ign_output_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0x002d, //  2: jmp    !x, 13
    0x80a0, //  3: pull   block
    0xa047, //  4: mov    y, osr
    0x0067, //  5: jmp    !y, 7
    0x0086, //  6: jmp    y--, 6
    0x80a0, //  7: pull   block
    0xa047, //  8: mov    y, osr
    0x006d, //  9: jmp    !y, 13
    0xa0e1, // 10: mov    osr, x
    0x6000, // 11: out    pins, 32
    0x008c, // 12: jmp    y--, 12
    0xa0e3, // 13: mov    osr, null
    0x6000, // 14: out    pins, 32
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ign_output_program = {
    .instructions = ign_output_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = ign_output_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ign_output_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ign_output_wrap_target, offset + ign_output_wrap);
    return c;
}

static inline void picospeed_decoder_program_init(PIO pio, uint sm, uint offset, uint pin, float div) {
    pio_sm_config c = picospeed_decoder_program_get_default_config(offset);
    sm_config_set_jmp_pin(&c, pin);
    sm_config_set_in_pins(&c, pin);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false); // INPUT
    sm_config_set_in_shift(&c, true, false, 32);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
// Perbaikan mutlak: Menambahkan fungsi konfigurasi set_out_pins agar instruksi 'out pins' bekerja
static inline void inj_output_program_init(PIO pio, uint sm, uint offset, uint pin_base, uint pin_count, float div) {
    pio_sm_config c = inj_output_program_get_default_config(offset);
    sm_config_set_out_pins(&c, pin_base, pin_count); // Wajib untuk instruksi "out pins"
    for(uint i = 0; i < pin_count; i++) {
        pio_gpio_init(pio, pin_base + i);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, pin_base, pin_count, true); // OUTPUT
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline void ign_output_program_init(PIO pio, uint sm, uint offset, uint pin_base, uint pin_count, float div) {
    pio_sm_config c = ign_output_program_get_default_config(offset);
    sm_config_set_out_pins(&c, pin_base, pin_count); // Wajib untuk instruksi "out pins"
    for(uint i = 0; i < pin_count; i++) {
        pio_gpio_init(pio, pin_base + i);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, pin_base, pin_count, true); // OUTPUT
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

